const c = [
  {
    producer: "SL RACK",
    title: "Anthrazit RAL 7016",
    price: 100,
    calculatorSection: "alpha_platte",
    angebotSection: "Zusatzarbeiten",
    material: "gewalztes Aluminiumblech",
    dimensions: "470 x 884 x 190 mm",
    weight: "1.14 kg",
    header: "Alpha-Platte",
    image: "platte.png",
  },
  {
    producer: "Enphase",
    title: "ENCHARGE-3T-1P-INT",
    price: 2750,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "3.5kWh",
    guarantee: "15 Jahre*",
    header: "Batteriesystem",
    image: "enphase-battery.png",
  },
  {
    producer: "Huawei",
    title: "LUNA2000-15-S0",
    price: 7900,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "15kWh",
    guarantee: "10 Jahre*",
    header: "Batteriesystem",
    image: "huawei5-15.png",
  },
  {
    producer: "Enphase",
    title: "ENCHARGE-10T-1P-INT",
    price: 7500,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "10.5kWh",
    guarantee: "15 Jahre*",
    header: "Batteriesystem",
    image: "enphase-battery.png",
  },
  {
    producer: "Huawei",
    title: "LUNA2000-5-S0",
    price: 3300,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "5kWh",
    guarantee: "10 Jahre*",
    header: "Batteriesystem",
    image: "huawei5-15.png",
  },
  {
    producer: "Tigo",
    title: "TSB-9",
    price: 5600,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "9.2kWh",
    guarantee: "11 Jahre*",
    header: "El Battery",
    image: "TigoBattery.png",
  },
  {
    producer: "Sungrow",
    title: "SBR096",
    price: 4900,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "9.6kWh",
    guarantee: "10 Jahre*",
    header: "Stromspeicher",
    image: "sungrow_batt.png",
  },
  {
    producer: "Sungrow",
    title: "SBR128",
    price: 6400,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "12.8kWh",
    guarantee: "10 Jahre*",
    header: "Stromspeicher",
    image: "sungrow_batt.png",
  },
  {
    producer: "Sungrow",
    title: "SBR192",
    price: 9550,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "19.2kWh",
    guarantee: "10 Jahre*",
    header: "Stromspeicher",
    image: "sungrow_batt.png",
  },
  {
    producer: "Sungrow",
    title: "SBR256",
    price: 14200,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "25.6kWh",
    guarantee: "10 Jahre*",
    header: "Stromspeicher",
    image: "sungrow_batt.png",
  },
  {
    producer: "Huawei",
    title: "LUNA2000-10-S0",
    price: 5900,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "10kWh",
    guarantee: "10 Jahre*",
    header: "Batteriesystem",
    image: "huawei5-15.png",
  },
  {
    producer: "Tigo",
    title: "TSB-6",
    price: 3400,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "6.1kWh",
    guarantee: "11 Jahre*",
    header: "El Battery",
    image: "TigoBattery.png",
  },
  {
    producer: "Sungrow",
    title: "SBR160",
    price: 8000,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "16kWh",
    guarantee: "10 Jahre*",
    header: "Stromspeicher",
    image: "sungrow_batt.png",
  },
  {
    producer: "Sungrow",
    title: "SBR224",
    price: 12650,
    calculatorSection: "batteries",
    angebotSection: "Components",
    storage: "22.4kWh",
    guarantee: "10 Jahre*",
    header: "Stromspeicher",
    image: "sungrow_batt.png",
  },
  {
    producer: "Solar Manager",
    title: " SM-1118-01",
    price: 1050,
    calculatorSection: "gateway",
    angebotSection: "Zusatzarbeiten",
    guarantee: "2 Jahre*",
    header: "Gateway",
    image: "solarManager.png",
  },
  {
    producer: "Tigo",
    title: "CCA",
    price: 240,
    calculatorSection: "gateway",
    angebotSection: "Zusatzarbeiten",
    guarantee: "12.8 Jahre*",
    header: "Tigo Cloud Connect Advanced (CCA)",
    image: "CCA.png",
  },
  {
    producer: "Enphase",
    title: "HEMS-GW-01",
    price: 480,
    calculatorSection: "gateway",
    angebotSection: "Zusatzarbeiten",
    guarantee: "5 Jahre*",
    header: "IQ Energy Router",
    image: "iqRouter.png",
  },
  {
    producer: "Enphase",
    title: "ENV-IQ-AM3-3P",
    price: 430,
    calculatorSection: "gateway",
    angebotSection: "Zusatzarbeiten",
    guarantee: "5 Jahre*",
    header: "IQ Gateway",
    image: "iqGateway.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-3KTL-M1",
    price: 1100,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "3.300VA",
    mpp: "2",
    max_efficiency: "98.2%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei3-10.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-5KTL-M1",
    price: 1280,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "5.500VA",
    mpp: "2",
    max_efficiency: "98.4%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei3-10.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-6KTL-M1",
    price: 1500,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "6.600VA",
    mpp: "2",
    max_efficiency: "98.6%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei3-10.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-30KTL-M3",
    price: 2650,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "33.000VA",
    mpp: "4",
    max_efficiency: "98.7%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei30-40.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-50KTL-M3",
    price: 3100,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "55.000VA",
    mpp: "6",
    max_efficiency: "98.7%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei50.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-8KTL-M1",
    price: 1750,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "8.800VA",
    mpp: "2",
    max_efficiency: "98.6%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei3-10.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-12KTL-M2",
    price: 1940,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "13.200VA",
    mpp: "2",
    max_efficiency: "98.5%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei12-20.png",
  },
  {
    producer: "Tigo",
    title: "TSI-6K3D",
    price: 2800,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "6.600VA",
    mpp: "2",
    max_efficiency: "98.2%",
    guarantee: "12.8 Jahre*",
    header: "Wechselrichter",
    image: "tigo.png",
  },
  {
    producer: "Sungrow",
    title: "SH6.ORT",
    price: 1880,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "6000VA",
    mpp: "2",
    max_efficiency: "98.2%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh.png",
  },
  {
    producer: "Sungrow",
    title: "SH8.ORT",
    price: 1980,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "8000VA",
    mpp: "2",
    max_efficiency: "98.4%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-17KTL-M2",
    price: 2120,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "18.700VA",
    mpp: "2",
    max_efficiency: "98.65%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: null,
  },
  {
    producer: "Huawei",
    title: "SUN2000-36KTL-M3",
    price: 2800,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "40.000VA",
    mpp: "4",
    max_efficiency: "98.7%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei30-40.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-40KTL-M3",
    price: 2900,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "44.000VA",
    mpp: "4",
    max_efficiency: "98.7%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei30-40.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-60KTL-M3",
    price: 3500,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "66.000VA",
    mpp: "6",
    max_efficiency: "98.9%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei50.png",
  },
  {
    producer: "Enphase",
    title: "IQ8HC-72-M-INT",
    price: 180,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "384VA",
    mpp: "1",
    max_efficiency: "97.4%",
    guarantee: "25 Jahre*",
    header: "Wechselrichter",
    image: "enphase-invent.png",
  },
  {
    producer: "Enphase",
    title: "IQ8AC-72-M-INT",
    price: 175,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "366VA",
    mpp: "1",
    max_efficiency: "97.3%",
    guarantee: "25 Jahre*",
    header: "Wechselrichter",
    image: "enphase-invent.png",
  },
  {
    producer: "Sungrow",
    title: "SH5.ORT",
    price: 1750,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "5000VA",
    mpp: "2",
    max_efficiency: "98.0%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh.png",
  },
  {
    producer: "Sungrow",
    title: "SH12ORT",
    price: 2100,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "8000VA",
    mpp: "2",
    max_efficiency: "98.4%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh.png",
  },
  {
    producer: "Sungrow",
    title: "SH20T",
    price: 3450,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "20000VA",
    mpp: "3",
    max_efficiency: "98.1%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh_t.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-4KTL-M1",
    price: 1200,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "4.400VA",
    mpp: "2",
    max_efficiency: "98.3%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei3-10.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-20KTL-M2",
    price: 2250,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "22.000VA",
    mpp: "2",
    max_efficiency: "98.65%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: null,
  },
  {
    producer: "Huawei",
    title: "SUN2000-10KTL-M1",
    price: 1850,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "11.000VA",
    mpp: "2",
    max_efficiency: "98.6%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei3-10.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-15KTL-M2",
    price: 2100,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "16.500VA",
    mpp: "2",
    max_efficiency: "98.65%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "huawei12-20.png",
  },
  {
    producer: "Tigo",
    title: "TSI-10K3D",
    price: 3500,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "11.000VA",
    mpp: "2",
    max_efficiency: "98.2%",
    guarantee: "12.8 Jahre*",
    header: "Wechselrichter",
    image: "tigo.png",
  },
  {
    producer: "Tigo",
    title: "TSI-15K3D",
    price: 4100,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "15.000VA",
    mpp: "2",
    max_efficiency: "98.2%",
    guarantee: "12.8 Jahre*",
    header: "Wechselrichter",
    image: "tigo.png",
  },
  {
    producer: "Sungrow",
    title: "SH15T",
    price: 3100,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "15000VA",
    mpp: "3",
    max_efficiency: "98.1%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh_t.png",
  },
  {
    producer: "Sungrow",
    title: "SH25T",
    price: 3700,
    calculatorSection: "inverters",
    angebotSection: "Components",
    power: "25000VA",
    mpp: "3",
    max_efficiency: "98.2%",
    guarantee: "10 Jahre*",
    header: "Wechselrichter",
    image: "sungrow_sh_t.png",
  },
  {
    producer: "Tigo",
    title: "TS4-A-O",
    price: 75,
    calculatorSection: "optimizers",
    angebotSection: "Components",
    guarantee: "11 Jahre*",
    header: "optimizers",
    image: "TS4.png",
  },
  {
    producer: "Tigo",
    title: "TAP",
    price: 60,
    calculatorSection: "optimizers",
    angebotSection: "Components",
    guarantee: "11 Jahre*",
    header: "Tigo Access Point (TAP)",
    image: "TAP.png",
  },
  {
    producer: "Huawei",
    title: "SUN2000-450w-P2",
    price: 70,
    calculatorSection: "optimizers",
    angebotSection: "Components",
    guarantee: "25 Jahre*",
    header: "Smart PV Optimizer",
    image: "450w.png",
  },
  {
    producer: "Huawei",
    title: "Backup Box-B1 ",
    price: 1500,
    angebotSection: "other",
    calculatorSection: "Zusatzarbeiten",
    guarantee: "10 Jahre*",
    header: "Backup Box",
    image: "backup.png",
  },
  {
    producer: "Enphase",
    title: "COMMS-KIT-01",
    price: 0,
    angebotSection: "other",
    calculatorSection: "Components",
    guarantee: "5 Jahre*",
    header: "Kommunikationskit",
    image: "backup.png",
  },
  {
    producer: "Huawei",
    title: "Smart Power Sensor DTSU666-HFE",
    price: 300,
    angebotSection: "smartmeters",
    calculatorSection: "Components",
    usage: "≤ 1 W",
    header: "Smart Meter",
    image: "smartMeter.png",
  },
  {
    producer: "Huawei",
    title: "Smart Power Sensor DTSU666-H 100A",
    price: 300,
    angebotSection: "smartmeters",
    calculatorSection: "Components",
    usage: "≤ 1 W",
    header: "Smart Meter",
    image: "smartMeter.png",
  },
  {
    producer: "Enphase",
    title: "CELLMODEM-M1-06-AT-05",
    price: 700,
    angebotSection: "iq_combiner",
    calculatorSection: "Components",
    description: "(Mobile Connect)",
  },
  {
    producer: "Enphase",
    title: "X-IQ-EURO-230-3P-4-1",
    calculatorSection: "Components",
    price: 2200,
    angebotSection: "iq_combiner",
    description: "(Gateway, COMMS-KIT, RELAY-3P)",
  },
  {
    producer: "Sungrow",
    title: "AC011E-01",
    price: 1130,
    angebotSection: "wallbox",
    calculatorSection: "Zusatzarbeiten",
    guarantee: "10 Jahre*",
    header: "Wallbox",
    image: "sungrow_wallbox.png",
  },
  {
    producer: "Huawei",
    title: "FusionCharge AC 22kW/32A",
    calculatorSection: "Zusatzarbeiten",
    price: 2000,
    angebotSection: "wallbox",
    guarantee: "10 Jahre*",
    header: "Wallbox",
    image: "huaweiWall.png",
  },
  {
    producer: "Pulsar Plus",
    title: "PLP1",
    price: 1500,
    angebotSection: "wallbox",
    calculatorSection: "Zusatzarbeiten",
    guarantee: "2 Jahre*",
    header: "Wallbox",
    image: "pulsar.png",
  },
];
const e = [
  {
    title: "Inbetriebnahme",
    price: 50,
    description: "(Ввод в эксплуатацию)",
    angebotSection: "Inbetriebnahme",
    calculatorSection: "Inbetriebnahme",
    specific: "single",
  },
  {
    title: "Anfahrt Elektriker",
    price: 550,
    description: "(подход электромонтера)",
    angebotSection: "Inbetriebnahme",
    calculatorSection: "Inbetriebnahme",
    specific: "single",
  },
  {
    title: "Montage, Verkabelung, Anschluss je Smartmeter",
    price: 50,
    description: "(Установка, прокладка кабелей, подключение счетчика)",
    angebotSection: "Inbetriebnahme",
    calculatorSection: "Inbetriebnahme",
    specific: "single",
  },
  {
    title: "Netzanmeldung",
    price: 105,
    description: "(регистрация в сети)",
    angebotSection: "Inbetriebnahme",
    calculatorSection: "Inbetriebnahme",
    specific: "single",
  },
  {
    title:
      "Projektierung, Kommunikation mit dem Netzbetreiber + Erstellung des Abschlussprotokolls",
    price: 500,
    description:
      "(планирование проекта, взаимодействие с сетевой компанией + Подготовка итогового отчета)",
    specific: "single",
    angebotSection: "Projektierung",
    calculatorSection: "Projektierung",
  },
  {
    title: "Montage, Verkabelung, Anschluss je Wechselrichter",
    price: 400,
    description:
      "(монтаж, подключение проводов и подключение самого инвертора)",
    specific: "single",

    angebotSection: "Installation + Lieferung",
    calculatorSection: "Installation + Lieferung",
  },
  {
    title: "Montage, Verkabelung, Anschluss je Stromspeicher",
    price: 400,
    description:
      "(монтаж, подключение проводов и подключение самого оптимайзера)",
    specific: "single",
    angebotSection: "Installation + Lieferung",
    calculatorSection: "Installation + Lieferung",
  },
  {
    title: "DC-Montage je Modul",
    price: 130,
    description: "(монтаж на крыше)",
    specific: "single",
    angebotSection: "Installation + Lieferung",
    calculatorSection: "Installation + Lieferung",
  },
  {
    title: "<5m",
    price: 400,
    description: "(леса меньше 5 метров)",
    specific: "select",
    angebotSection: "Installation + Lieferung",
    calculatorSection: "Installation + Lieferung",
  },
  {
    title: "5-8m",
    price: 500,
    description: "(леса от 5-8 метров)",
    specific: "select",
    angebotSection: "Installation + Lieferung",
    calculatorSection: "Installation + Lieferung",
  },
  {
    title: ">8m",
    price: 600,
    description: "(леса больше 8 метров)",
    specific: "select",
    angebotSection: "Installation + Lieferung",
    calculatorSection: "Installation + Lieferung",
  },
  {
    title: "Quermontage",
    price: 220,
    description: "(модули лежа)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Hochmontage",
    price: 190,
    description: "(модули стоя)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Trapezdach",
    price: 68,
    description: "(трапециевидная крыша)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Flachdach Ost/West",
    price: 160,
    description: "(на плоской крыше)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Hochmontage Alpha",
    price: 230,
    description: "(высокие монтажные альфа-панели)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Trapezdach Alpha",
    price: 95,
    description: "(трапециевидная крыша Альфа)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Flachdach Alpha",
    price: 190,
    description: "(плоская кровля Альфа)",
    specific: "single",
    angebotSection: "Unterkonstruktion",
    calculatorSection: "Unterkonstruktion",
  },
  {
    title: "Trina Glas-Glas Module 440W",
    price: 220,
    description: "(модуль)",
    specific: "single",
    angebotSection: "PV-Module",
    calculatorSection: "PV-Module",
  },
  {
    title: "Jolywood JW-HD108N-420W Full black glas-glas",
    price: 250,
    description: "(модуль)",
    specific: "single",
    angebotSection: "PV-Module",
    calculatorSection: "PV-Module",
  },
  {
    title: "240 mm Spitzen",
    price: 18,
    description: "(наконечники 240 мм)",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Taubenschutz",
  },
  {
    title: "Material + Montage je Laufmeter",
    price: 228,
    description: "(материал и монтаж за погонный метр)",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Taubenschutz",
  },
  {
    title: "Überspannungsschutz Typ 1+2 installieren",
    price: 415,
    description: "Установите защиту от перенапряжения типа 1+2",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Zusatzarbeiten",
  },
  {
    title: "SLS Schalter installieren",
    price: 135,
    description: "Установите переключатель SLS",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Zusatzarbeiten",
  },
  {
    title: "Kaskadenschaltung",
    price: 1000,
    description: "(каскадное соединение)",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Zusatzarbeiten",
  },
  {
    title: "Zählerkasten nach VDE-Norm",
    price: 2380,
    description: "(расходомерная коробка в соответствии со стандартом VDE)",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Zusatzarbeiten",
  },
  {
    title: "Versetzen einer SAT-Schlüssel",
    price: 250,
    description: "Перемещение клавиши SAT",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Zusatzarbeiten",
  },
  {
    title: "Potentialausgleich mit Erdungsspieß setzen",
    price: 300,
    description:
      "(установить выравнивание потенциалов с помощью заземляющего колышка)",
    specific: "single",
    angebotSection: "Zusatzarbeiten",
    calculatorSection: "Zusatzarbeiten",
  },
];
